site_name: DRF Training Guide
site_url: https://pragnakalpdev54.github.io/DRF/
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - navigation.footer  

nav:
  - Home: index.md
  - Level 0 – Beginner: LEVEL_0_BEGINNER.md
  - Level 1 – Foundations: LEVEL_1_FOUNDATIONS.md
  - Level 2A – Core: LEVEL_2A_INTERMEDIATE.md
  - Level 2B – Applied: LEVEL_2B_INTERMEDIATE.md
  - Level 3A – Internals: LEVEL_3A_ADVANCED.md
  - Level 3B – Security: LEVEL_3B_ADVANCED.md
  - Level 4 – Scalable: LEVEL_4_SCALABLE.md
  - Level 5 – Expert: LEVEL_5_EXPERT.md
  - PostgreSQL: POSTGRESQL_SETUP.md
  - Postman Basics: POSTMAN_GUIDE_PART1_BASICS.md
  - Postman Advanced: POSTMAN_GUIDE_PART2_ADVANCED.md
  - cURL Guide: CURL_GUIDE.md
 
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - footnotes
  - codehilite


extra_css:
  - assets/stylesheets/footer.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/sidebar.css 
